apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJZWE4xY21GdU9tZG9jRjl0VG5CQ2VXcFFRVkZqZEhkcU1tWkZSakoxUzJwWE5FVmxSbEp0V0RFemIxcDRTekU9In19fQo=
type: kubernetes.io/dockerconfigjson
