apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJZWE4xY21GdU9tZG9jRjl0VG5CQ2VXcFFRVkZqZEhkcU1tWkZSakoxUzJwWE5FVmxSbEp0V0RFemIxcDRTekU9IgogICAgfQogIH0KfQo=
type: kubernetes.io/dockerconfigjson
